[package]
name = "chirpy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
image = "0.25.6"
infer = "0.19.0"
lofty = "0.22.4"
mime_guess = "2.0.5"
ratatui = "0.29.0"
ratatui-image = "8.0.1"
rodio = "0.20.1"
rustfft = "6.2.0"
ringbuf = "0.4.7"
